[project]
name = 'waffle_contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.access_control]
path = 'contracts/access_control.clar'
clarity_version = 2
epoch = 2.5

[contracts.audit_trail_wallet]
path = 'contracts/audit_trail_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.historical_snapshots]
path = 'contracts/historical_snapshots.clar'
clarity_version = 2
epoch = 2.5

[contracts.multi_send_with_role_based_access]
path = 'contracts/multi_send_with_role_based_access.clar'
clarity_version = 2
epoch = 2.5

[contracts.start_and_end_time]
path = 'contracts/start_and_end_time.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_and_admin_role]
path = 'contracts/storage_and_admin_role.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
